version: "3.0"

services:
  service:
    env_file:
      - ".docker-compose-env"
    build:
      context: 'service'
      dockerfile: 'Dockerfile'
    command: [ "uvicorn", "service.main:app", "--host", "0.0.0.0", "--port", "8192" ]
    environment:
      - CORS_ALLOWED_DOMAINS="http://localhost:8192"
    ports:
      - "8192"
    volumes:
      - assets-data:/data/results

  console:
    env_file:
      - ".docker-compose-env"
    build:
      context: 'service'
      dockerfile: 'Dockerfile'
    command: [ "/bin/sh" ]
    volumes:
      - assets-data:/data/results

  font-asset-creation:
    env_file:
      - ".docker-compose-env"
    build:
      context: 'service'
      dockerfile: 'Dockerfile'
    entrypoint: [ "python3", "font-asset-creation.py" ]
    volumes:
      - ./assets/:/data/results

volumes:
  assets-data:
    driver: local
